service: xtream-m3u8

frameworkVersion: '2'

provider:
  name: aws
  runtime: python3.8
  lambdaHashingVersion: 20201221
  stage: prod
  region: eu-west-2
  memorySize: 128

plugins:
  - serverless-wsgi
  - serverless-python-requirements

functions:
  api:
    handler: wsgi_handler.handler
    events:
      - http: ANY /
      - http: ANY {proxy+}

custom:
  wsgi:
    app: server.app
    pythonBin: python3
    packRequirements: false

  pythonRequirements:
    dockerizePip: non-linux
