service: xtream-iptv-proxy

frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.8
  stage: prod
  region: eu-west-2
  memorySize: 128

plugins:
  - serverless-wsgi
  - serverless-python-requirements

functions:
  api:
    handler: wsgi_handler.handler
    events:
      - http: ANY /
      - http: ANY /{proxy+}

custom:
  wsgi:
    app: server.app
    pythonBin: python3
    packRequirements: false
    textMimeTypes:
      - application/x-mpegURL

  pythonRequirements:
    dockerizePip: non-linux
